drop table if exists PlayerIDs;

CREATE TABLE playerids (
        mlb_id text not null primary key,
        mlb_name text,
        mlb_pos text,
        mlb_team text,
        mlb_team_long text,
        bats text,
        throws text,
        birth_year text,
        bp_id text,
        bref_id text,
        bref_name text,
        cbs_id text,
        cbs_name text,
        cbs_pos text,
        espn_id text,
        espn_name text,
        espn_pos text,
        fg_id text,
        fg_name text,
        fg_pos text,
        lahman_id text,
        nfbc_id text,
        nfbc_name text,
        nfbc_pos text,
        retro_id text UNIQUE,
        retro_name text,
        debut text,
        yahoo_id text,
        yahoo_name text,
        yahoo_pos text,
        mlb_depth text,
        ottoneu_id text,
        ottoneu_name text,
        ottoneu_pos text,
        rotowire_id text,
        rotowire_name text,
        rotowire_pos text
);
